#!/bin/dash
#if before commit and after commit is different it should print commitd as commit number else print nothing to commit
#Start from 0 and increase the number which will be substitution of sentence
#Should save commit number and message
#if [ $1 = "-m" ]; then
#    if []; then  
#         echo "Committed as commit 0"
#    fi
#fi


#if [ ! -d commitX ]; then
 #   mkdir commitX	
#fi

i=0 #have to write for loop to find commit number
for dir in commit*/ ; do
    if [ -d commit0 ]; then    
        i=$(($i+1))
    fi
done
#echo $i 
cp -r .girt commit$i
if [ ! -d commit$(($i-1)) ]; then
    echo "Committed as commit 0"
else
    msg=$(diff commit$(($i-1)) commit$i)
    if [ -z $msg ]; then
       echo "nothing to commit"
    else
        echo "Committed as commit $(($i-1))"
    fi
fi
#else	
#    echo "Committed as commit $i"
#fi
#message & if nothing to commit then what is $i



#for file in $@; do #save snapshot (each commits)
 #   cd commit$i
  #  cp ${file} commitx/
    #save commit message and print it to girt-log
#done

#diff -r commit$i commit$(i+1) #directory comparison to confirm change
#if []; then
#    echo "nothing to commit"
#else
#    echo "Committed as commit $i"

