#!/bin/dash


if [ -d .girt ]; then
    if [ ! -f $1 ]; then
        echo "girt-add: error: can not open 'non_existent_file'"
        exit 1
    else
        for file in $@; do
            if [ ! -d .girt/index/$file ]; then
                mkdir .girt/index/$file
            fi

            if [ -f .girt/index/$file/latest ]; then
                d=$(diff -s a .girt/index/a/latest|cut -d' ' -f1)
                if [ ! $d = "Files" ]; then
                   # echo "Two files are different"
                    cp $file .girt/index/$file/change
                fi
            else
               # echo "There's no latest"
                cp $file .girt/index/$file/change
            fi
        done
    fi
else
	echo "girt-add: error: girt repository directory .girt not found"
fi
